### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by xaionaro** [jszum/CsvToWav#1]
How to use it?

```
148 d[19:42:15] [xaionaro@imperium ~/CsvToWav]$ python ./converter.py /tmp/3.csv
Path: ./converter.py/tmp/3.csv
Traceback (most recent call last):
  File "./converter.py", line 58, in <module>
    main(sys.argv[1])
  File "./converter.py", line 48, in main
    data = convert(csvfile)
  File "./converter.py", line 22, in convert
    rawdata[i].append( int(fields[i]) )
OverflowError: signed short integer is greater than maximum
```

**Comment by jszum** [comment]
You did well, but you have in your csv numbers greater than short int. I coded this script for specific purpose, so if you want to use it differently, just let me know.

EDIT: For now it will be enough to recode this:

```
    rawdata.append( array.array('h') )
    # 'h' implies that there will be short ints, so just use the letter that you need
```
